### ISSUE TITLE
Segfault on texture load

### ISSUE THREAD

**Issue by rantonels** [MasterQ32/VersaTile#35]
64bit Linux.

VersaTile works fine with default tileset.

When a new image is selected as a new texture (either by creating a new file or by attempting to switch textures on an existing one), the following error pops up in console:

```
...
"FS SIMD8 shader: 107 inst, 0 loops, 350 cycles, 0:0 spills:fills, Promoted 1 constants, compacted 1712 to 1152 bytes."
"FS SIMD16 shader: 110 inst, 0 loops, 532 cycles, 0:0 spills:fills, Promoted 1 constants, compacted 1760 to 1200 bytes."
QPainter::begin: Cannot paint on an image with the QImage::Format_Indexed8 format
QPainter::setCompositionMode: Painter not active
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
QColor::setRgb: RGB parameters out of range
...
```

and the preview is completely black (with horizontal grid lines visible on black). When I click to confirm loading, program segfaults.

This has been tested with both an indexed .png and a .bmp, with identical result.

**Comment by ikskuh** [comment]
It looks like the problem is the indexed image format. Can you upload a reference image with which this crash happens?

**Comment by rantonels** [comment]
Ok, you're absolutely right, it's the indexing that's the problem. Here's my indexed .png that triggers the issue:

![indexed](http://i.imgur.com/a0IviKG.png)

and here I've converted it into 32-bit RGBA, which works fine, preview is ok, no segfault, can use it in editor:

![32bit](http://i.imgur.com/7P0Zm4O.png)

Looks like it's trying to load the indexed image as if it was RGB.

**Comment by ikskuh** [comment]
Nah, it's trying to access the image like it's an RGB index. But i can overcome this issue by just convert the image to RGB space on load

**Comment by rantonels** [comment]
fantastic, thank you

**Comment by ikskuh** [comment]
Should be resolved with 2106a52c61a6fc067f207fdd65271a90b62f1e5d. Would be nice if you could check if it works now... ;)

**Comment by rantonels** [comment]
I confirm 2106a52c61a6fc067f207fdd65271a90b62f1e5d works as expected with indexed image

P.S.: `QColor::setRgb: RGB parameters out of range` still appears in the console.
